### ISSUE TITLE
Soft 15

### ISSUE THREAD

**Issue by andreadpan** [SailorSat/soft-15khz#1]
Hello Ariane 
I want put computer on tv by vga >scart 
I think tv is 31khz i'm not sure , tv is 15khz 
Computer acer aspire one d257 
Just i clic on 15khz in your soft 15 khz , active 15khz, and that s good?

**Comment by SailorSat** [comment]
Your netbook has an Intel HD graphics chip, which is partially supported at best, and it only allow for up to 5 custom resultions (if any).

It most likely wont work.

**Comment by Darthbiker** [comment]
Hi sailorsat, I need an edid dongle to run soft 15khz on my pc, I would be very grateful if you could make me one.  I am from Spain
